# Generated by Django 5.0.1 on 2024-10-27 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('nom', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('fournisseur', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantiteStock', models.IntegerField()),
                ('produitStock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GestStock.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informationTransaction', models.CharField(max_length=256)),
                ('typeTransaction', models.CharField(max_length=128)),
                ('quantiteTransaction', models.IntegerField()),
                ('montantTransaction', models.FloatField()),
                ('dateTransaction', models.DateTimeField()),
                ('produitTransaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GestStock.produit')),
            ],
        ),
    ]
