# Generated by Django 5.0.1 on 2024-10-29 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestStock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomFournisseur', models.CharField(max_length=128)),
                ('telephoneFournisseur', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='produit',
            name='fournisseur',
        ),
        migrations.CreateModel(
            name='TransactionAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreation', models.DateTimeField(auto_created=True)),
                ('informationTransaction', models.CharField(max_length=256)),
                ('quantiteTransaction', models.IntegerField()),
                ('montantTransaction', models.FloatField()),
                ('dateTransaction', models.DateTimeField()),
                ('fournisseurTransactionAchat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GestStock.fournisseur')),
                ('produitTransaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GestStock.produit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreation', models.DateTimeField(auto_created=True)),
                ('informationTransaction', models.CharField(max_length=256)),
                ('quantiteTransaction', models.IntegerField()),
                ('montantTransaction', models.FloatField()),
                ('dateTransaction', models.DateTimeField()),
                ('produitTransaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GestStock.produit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
