# Generated by Django 5.0.1 on 2024-11-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestStock', '0003_produit_quantitestock_alter_produit_nom_delete_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionvente',
            name='margeVente',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantiteStock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transactionachat',
            name='dateCreation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transactionachat',
            name='informationTransaction',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='transactionachat',
            name='quantiteTransaction',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transactionvente',
            name='dateCreation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transactionvente',
            name='informationTransaction',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='transactionvente',
            name='quantiteTransaction',
            field=models.PositiveIntegerField(),
        ),
    ]
