# Generated by Django 5.0.1 on 2024-11-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestStock', '0004_transactionvente_margevente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionachat',
            name='montantTransaction',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionvente',
            name='margeVente',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionvente',
            name='montantTransaction',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
